spring:
  application:
    name: Spring_security
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456789
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true


logging:
  level:
    org:
      springframework:
        security: DEBUG